# Generated by Django 4.0.2 on 2023-03-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
                ('zipcode', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, 'matematyka'), (2, 'j. polski'), (3, 'j. angielski'), (4, 'biologia'), (5, 'chemia'), (6, 'fizyka'), (7, 'historia'), (8, 'geografia'), (9, 'wiedza o społeczeństwie'), (10, 'informatyka'), (11, 'j. hiszpańśki'), (12, 'j. rosysjki'), (13, 'j. niemiecki')])),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameandsurname', models.CharField(max_length=64)),
                ('contact', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='korki.city')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korki.tutor')),
                ('subject', models.ManyToManyField(to='korki.Subject')),
            ],
        ),
    ]
