# Generated by Django 4.0.2 on 2023-03-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='contact',
        ),
    ]
