# Generated by Django 4.0.2 on 2023-04-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.IntegerField(choices=[('matematyka', 'matematyka'), ('j. polski', 'j. polski'), ('j. angielski', 'j. angielski'), ('biologia', 'biologia'), ('chemia', 'chemia'), ('fizyka', 'fizyka'), ('historia', 'historia'), ('geografia', 'geografia'), ('wiedza o społeczeństwie', 'wiedza o społeczeństwie'), ('informatyka', 'informatyka'), ('j. hiszpańśki', 'j. hiszpańśki'), ('j. rosysjki', 'j. rosysjki'), ('j. niemiecki', 'j. niemiecki')]),
        ),
    ]
