# Generated by Django 4.0.2 on 2023-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korki', '0002_remove_city_city_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='postcode',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
